version: "3"
services:

  server:
    build:
        context: ./server
    container_name: microservice-server
    ports:
      - "8761:8761"
    networks: 
      - network-eureka

  sum:
    build:
        context: ./sum
    container_name: microservice-sum
    ports:
      - "8082:8082"
    networks: 
      - network-eureka
    environment:
      - EUREKA_SERVICE_URL=http://server:8761
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true

  subtract:
    build:
        context: ./subtract
    container_name: microservice-subtract
    ports:
      - "8083:8083"
    networks: 
      - network-eureka
    environment:
      - EUREKA_SERVICE_URL=http://server:8761
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true

  multiple:
    build:
        context: ./multiple
    container_name: microservice-multiple
    ports:
      - "8084:8084"
    networks: 
      - network-eureka
    environment:
      - EUREKA_SERVICE_URL=http://server:8761
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true

  division:
    build:
        context: ./division
    container_name: microservice-division
    ports:
      - "8085:8085"
    networks: 
      - network-eureka
    environment:
      - EUREKA_SERVICE_URL=http://server:8761
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true

  calculator:
    build:
        context: ./calculator
    container_name: microservice-calculator
    ports:
      - "8081:8081"
    networks: 
      - network-eureka
    environment:
      - EUREKA_SERVICE_URL=http://server:8761
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true

networks: 
    network-eureka: